# Generated by Django 4.1.3 on 2022-11-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
