# Generated by Django 4.1.3 on 2022-12-25 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sql', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='erdiagram',
            unique_together={('name', 'user')},
        ),
    ]
